# Generated by Django 5.0 on 2025-10-14 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sneaker_shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
