# Generated by Django 5.0 on 2025-10-28 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneaker_shop', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='sli_description',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='sli_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
