# Generated by Django 5.0 on 2025-11-17 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneaker_shop', '0005_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('content_rev', models.TextField()),
                ('rating', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
