# Generated by Django 5.0 on 2025-11-10 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_options_product_is_sale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pin_code',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
